var breachReasons = [
    "Lack of Data Encryption",
    "Poor Password Management",
    "Lack of Regular Security Audits",
    "Outdated Security Systems",
    "Employee Negligence",
    "Not Patching Software Vulnerabilities",
    "Inside Jobs",
    "Insufficient Employee Training",
    "Phishing Attacks",
    "Malware Infections",
    "Ransomware Attacks",
    "Unsecured Network Connections",
    "Lack of Multi-Factor Authentication",
    "SQL Injection Attacks",
    "Zero-Day Exploits",
    "Use of Default Passwords",
    "Failure to Backup Data Regularly",
    "Use of Outdated Operating Systems",
    "Brute Force Attacks",
    "Unsecured APIs",
    "Third-Party Data Breaches",
    "Poor Physical Security",
    "Misconfigured Cloud Storage",
    "Denial of Service (DoS) Attacks",
    "Compromised Email Accounts",
    "Social Engineering Attacks",
    "Use of Public Wi-Fi Networks",
    "Failure to Update Firewall Rules",
    "Accidental Data Exposure",
    "Man-in-the-Middle (MitM) Attacks",
    "Lack of Security Incident Response Plan",
    "Cross-Site Scripting (XSS) Attacks",
    "Unsecured Mobile Devices",
    "Unprotected IoT Devices",
    "Not Complying with Industry Security Standards",
    "Inadequate Monitoring and Logging",
    "Supply Chain Attacks",
    "AI-Powered Cyber Attacks",
    "Weak Network Infrastructure",
    "Poor Data Disposal Practices",
    "Cryptocurrency Mining Malware",
    "Use of Outdated Hardware",
    "Shadow IT",
    "Insufficient Budget for Cybersecurity",
    "Distributed Denial of Service (DDoS) Attacks",
    "Stolen or Lost Devices",
    "Hacker Group Attacks",
    "Unpatched Third-Party Software",
    "Failure to Encrypt Sensitive Data",
    "Exposed Sensitive Information Online",
    "Weak Security Policies",
    "Reused Passwords Across Multiple Accounts",
    "Lack of a Strong Security Culture",
    "Clicking on Malicious Links",
    "Downloading Suspicious Email Attachments",
    "Insider Threats",
    "AI and Machine Learning Vulnerabilities",
    "Bring Your Own Device (BYOD) Policy Gaps",
    "Failure to Follow Cybersecurity Best Practices",
    "Weak Endpoint Security",
    "Poor Vendor Risk Management",
    "Not Regularly Reviewing User Access Rights",
    "Fake Antivirus Software",
    "Malicious Chatbots",
    "Failure to Install Antivirus Software",
    "Failure to Recognize Suspicious Activity",
    "Lack of Employee Cybersecurity Awareness",
    "Failure to Regularly Change Passwords",
    "Ignoring Regular Software Updates",
    "Not Securing Remote Work Environments",
    "The janitor misplaced the 'Top Secret' folder",
    "Someone unplugged the security server to charge their phone",
    "The office dog ate the firewall",
    "A squirrel chewed through the main internet cable",
    "The intern clicked on a 'You've won a million dollars!' email",
    "A UFO caused a major electrical interference",
    "They thought 'password123' was unbreakable",
    "The firewall subscription expired and nobody noticed",
    "The printer revolted and started sending confidential documents",
    "A random cat walked over the keyboard and somehow crashed the server",
    "Big data: it was just too big to handle",
    "Someone spilled coffee on the main server",
    "The security camera was focused on the office plant instead of the entrance",
        "An army of hacker mice",
    "Failed to install updates because 'it's too time-consuming'",
    "Forgot to renew the domain name, and it got squatted",
    "The office pet parrot learned and shared the CEO's password",
    "Aliens used advanced technology to breach the servers",
    "The office fortune teller predicted a secure year. She was wrong.",
    "Instead of a sandbox environment, they accidentally used the production server for testing",
    "Someone thought GDPR was a new kind of coffee and ignored it",
    "The firewall was accidentally replaced with a literal wall of fire",
    "Artificial Intelligence became a little too intelligent",
    "There was a 'Bring Your Hacker to Work Day'",
    "The sticky note with all the passwords was accidentally thrown away",
    "The company hired a 'security expert' from a popup ad",
    "The office plant turned out to be a mole plant, recording all conversations",
    "They forgot to secure the 'Internet of Toasters'",
    "Someone installed 'Virus.exe' thinking it was antivirus software",
    "A game of office tag resulted in the server room door being left open",
    "All the employees were at an office party when the breach happened",
    "The cybersecurity officer was too busy playing solitaire",
    "Someone used 'password' as their password",
    "The office fish was a covert operative for a rival company",
    "The janitor accidentally swept up the secure server into the trash",
    "There was a 'Click this suspicious link' contest in the office",
    "A disgruntled office cat knocked over the server",
    "The AI got too emotional and let the hackers in",
    "An intern was convinced 'Hacker' was a job title in the company",
    "The office decided to let 'Fate' handle all cybersecurity matters",
    "Someone decided to use a Ouija board for their password",
    "The password was written on a billboard right outside the office",
    "A psychic predicted the password",
    "The password was the name of the company",
    "The coffee machine was wired into the network and spilled the beans",
    "All passwords were changed to '123456' because it was easier to remember",
    "The Wi-Fi password was 'Password'",
    "A rogue Roomba was found to be collecting data",
    "The company relied on luck for cybersecurity",
    "An office plant turned out to be a secret agent",
    "The IT team was too busy watching cat videos",
    "The firewall was turned off to speed up the internet",
    "A visiting dog was a secret agent",
    "Someone didn't want to read the 'Boring' security manual",
    "The security officer was on a coffee break during the breach",
    "They let a wizard handle their cybersecurity",
    "Someone ignored the 'This site is insecure' warning",
    "Someone forgot to turn the security systems back on after a test",
    "The company believed they were 'too small' to be targeted",
    "A lucky guess on the password",
    "Too busy celebrating 'National Donut Day' to notice the breach",
    "The server was used as a coaster during a party",
    "A hamster chewed through the network cables",
    "The company thought that a firewall was an actual wall made of fire",
    "The IT department was replaced by a magic 8-ball",
    "A seagull stole the office master password",
    "The company believed that 'security' was a type of coffee",
    "Someone took 'Open Source' too literally and made everything open",
    "Company used a time machine to go back in time but forgot to patch old vulnerabilities",
    "A 'guess the password' competition was held at a public event",
    "An evil twin of the CEO infiltrated the office",
    "The antivirus software was actually just a video of a cartoon police officer",
    "A kid on a tour guessed the admin password on their first try",
    "Someone sent the secure password through a postcard",
    "The company thought CAPTCHA was enough to stop all cyber attacks",
    "The office gnome came to life and stole the password",
    "They used 'admin' and '123456' as their username and password because it was easy to remember",
    "An employee was using the company server to host a gaming tournament",
    "The password was taped to the bottom of the keyboard",
    "The free Wi-Fi in the office had no password",
    "The company security policy was written in an unknown language",
    "The company's 'unhackable' claim was taken as a challenge",
    "Everyone was too busy watching a sports game on TV to notice the breach",
    "An employee was live-tweeting their work day, including typing in the password",
    "An intern mistook the server room for a storage closet",
    "The security team was distracted by a cute puppy video",
    "A rogue smart fridge ordered a security breach along with the groceries",
    "The office assistant revealed the password during a trivia game",
    "The boss didn't want to 'bother' employees with password updates",
    "A disgruntled vending machine launched a cyber attack",
    "The intern forgot to log out of the admin account at a public cafe",
    "An owl from a wizarding school delivered a malware-laden letter",
    "The cybersecurity plan was stored in a file named 'totally_not_the_cybersecurity_plan.docx'",
    "The office ghost haunted the main server",
    "The CISO's 'My password is secure' mug had the actual password written on the bottom",
    "Someone left the virtual front door open",
    "The company used a cybersecurity solution they bought from a guy in a trench coat",
    "A bird flew into a window and somehow caused a power surge",
    "They used a decoder ring from a cereal box to encrypt data",
    "The cybersecurity team was on a team-building retreat",
    "Someone clicked on a banner ad promising to 'clean the computer'",
    "An employee saved all the passwords in a file named 'passwords.txt'",
    "The company used a dartboard to make cybersecurity decisions",
    "Someone let a spider spin a web in the server room",
    "They ignored all the warnings because they were 'annoying'",
    "They forgot to log out after using a public computer",
    "A clairvoyant called and they gave her the password",
    "The boss decided to replace the IT department with his tech-savvy nephew",
    "The intern was convinced 'Trojan Horse' was a new game",
    "They stored all their data on a floppy disk that got lost",
    "An office-wide scavenger hunt led to the server room",
    "A monkey was hired to increase productivity but ended up causing a security breach",
    "The office used the same key for the front door and their encryption"
]

